data:
  # 原始数据
  train_data: "data/raw/train_data.csv"
  test_data: "data/raw/test_data.csv"
  # 初步数据探索和清洗后的数据
  train_cleaned: "data/processed/cleaned/train_cleaned.csv"
  test_cleaned: "data/processed/cleaned/test_cleaned.csv"

  processed: "data/processed"

model:
  model_name: "bert-base-chinese"
  max_length: 256
  batch_size: 16
  learning_rate: 2e-5
  num_epochs: 3
  hidden_dropout_prob: 0.1

attack:
  method: "white_box"  # 第一阶段目标
  max_iterations: 5  # 对一条文本进行攻击时，最多进行的迭代轮数
  beam_size: 2  # 在每一轮迭代中，要保留的最优候选样本的数量
  max_candidates: 50  # 对于每一个待替换的词，使用BERT-MLM模型生成的最大候选同义词数量
  similarity_threshold: 0.7  # 语义相似度阈值（硬约束验证中）